const importPlugin = require('eslint-plugin-import');
const unusedImportPlugin = require('eslint-plugin-unused-imports');
const simpleImportsSortPlugin = require('eslint-plugin-simple-import-sort');

module.exports = {
  plugins: {
    import: importPlugin,
    'unused-imports': unusedImportPlugin,
    'simple-import-sort': simpleImportsSortPlugin,
  },
  settings: {
    'import/parsers': { '@typescript-eslint/parser': ['.ts'] },
    'import/resolver': {
      'eslint-import-resolver-typescript': true,
      typescript: {
        alwaysTryTypes: true,
      },
    },
  },
  rules: {
    'import/no-commonjs': 'error',
    'import/no-cycle': 'off',
    'import/no-self-import': 'error',
    'unused-imports/no-unused-imports': 'error',
    'unused-imports/no-unused-vars': 'warn',
    'import/no-mutable-exports': 'error',
    'import/no-named-as-default-member': 'error',
    'import/no-unused-modules': 'error',
    'import/no-absolute-path': 'error',
    'import/no-useless-path-segments': 'error',
    'import/first': 'error',
    'import/no-default-export': 'error',
    'import/no-duplicates': 'error',
    'import/no-unassigned-import': 'error',
    'import/no-webpack-loader-syntax': 'error',
    'import/no-relative-packages': 'error',
    'import/newline-after-import': ['error', { count: 1 }],
    'import/named': 'error',
    'import/max-dependencies': 'off',
    'import/no-unresolved': 'warn',
    'import/no-deprecated': 'off',
    'import/no-extraneous-dependencies': [
      'warn',
      {
        devDependencies: [
          'test/**',
          'tests/**',
          'spec/**',
          '**/__tests__/**',
          '**/__mocks__/**',
          'test.{js,jsx}',
          'test.{ts,tsx}',
          'test-*.{js,jsx}',
          'test-*.{ts,tsx}',
          '**/*{.,_}{test,spec}.{js,jsx}',
          '**/*{.,_}{test,spec}.{ts,tsx}',
          '**/jest.config.js',
          '**/jest.config.ts',
          '**/jest.setup.js',
          '**/jest.setup.ts',
          '**/vue.config.js',
          '**/vue.config.ts',
          '**/webpack.config.js',
          '**/webpack.config.ts',
          '**/webpack.config.*.js',
          '**/webpack.config.*.ts',
          '**/rollup.config.js',
          '**/rollup.config.ts',
          '**/rollup.config.*.js',
          '**/rollup.config.*.ts',
          '**/gulpfile.js',
          '**/gulpfile.ts',
          '**/gulpfile.*.js',
          '**/gulpfile.*.ts',
          '**/Gruntfile{,.js}',
          '**/Gruntfile{,.ts}',
          '**/protractor.conf.js',
          '**/protractor.conf.ts',
          '**/protractor.conf.*.js',
          '**/protractor.conf.*.ts',
          '**/karma.conf.js',
          '**/karma.conf.ts',
          '**/.eslintrc.js',
          '**/.eslintrc.ts',
        ],
        optionalDependencies: false,
      },
    ],
    'import/order': 'off',
    'simple-import-sort/imports': 'error',
    'simple-import-sort/exports': 'error',
    'import/extensions': [
      'error',
      {
        json: 'always',
        js: 'never',
        ts: 'never',
      },
    ],
    'import/namespace': 'off',
  },
};
