module.exports = {
    'no-redeclare': 'off',
    'no-throw-literal': 'off',
    'no-useless-constructor': 'off',
    'no-dupe-class-members': 'off',
    'no-extra-boolean-cast': 'off',
    '@typescript-eslint/no-inferrable-types': 'off',
    '@typescript-eslint/strict-boolean-expressions': 'off',
    '@typescript-eslint/no-dupe-class-members': 'error',
    '@typescript-eslint/no-redeclare': 'error',
    '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'off',
    '@typescript-eslint/no-useless-constructor': 'error',
    '@typescript-eslint/explicit-function-return-type': 'error',
    '@typescript-eslint/no-confusing-non-null-assertion': 'error',
    '@typescript-eslint/no-duplicate-enum-values': 'error',
    '@typescript-eslint/no-invalid-void-type': 'error',
    '@typescript-eslint/no-base-to-string': 'error',
    '@typescript-eslint/no-for-in-array': 'error',
    '@typescript-eslint/no-misused-promises': 'error',
    '@typescript-eslint/no-require-imports': 'error',
    '@typescript-eslint/no-this-alias': 'error',
    '@typescript-eslint/no-useless-empty-export': 'error',
    '@typescript-eslint/no-var-requires': 'error',
    '@typescript-eslint/non-nullable-type-assertion-style': 'off',
    '@typescript-eslint/prefer-function-type': 'error',
    '@typescript-eslint/prefer-ts-expect-error': 'error',
    '@typescript-eslint/unified-signatures': 'error',
    '@typescript-eslint/prefer-optional-chain': 'warn',
    'no-console': 'warn',
    '@typescript-eslint/require-array-sort-compare': [
      'error',
      { ignoreStringArrays: true },
    ],
    '@typescript-eslint/no-confusing-void-expression': [
      'error',
      { ignoreArrowShorthand: true },
    ],
    '@typescript-eslint/no-explicit-any': [
      'warn',
      { fixToUnknown: false, ignoreRestArgs: true },
    ],
    '@typescript-eslint/typedef': [
      'error',
      {
        memberVariableDeclaration: true,
        variableDeclaration: false,
        parameter: true,
        propertyDeclaration: true,
      },
    ],
    '@typescript-eslint/naming-convention': [
      'error',
      {
        selector: 'enum',
        format: ['PascalCase'],
        prefix: ['En'],
      },
      {
        selector: 'typeLike',
        format: ['StrictPascalCase'],
      },
      {
        selector: 'method',
        format: ['camelCase'],
        leadingUnderscore: 'allow',
      },
      {
        selector: 'property',
        format: ['camelCase', 'UPPER_CASE'],
        leadingUnderscore: 'allowSingleOrDouble',
      },
      {
        selector: 'property',
        format: null,
        modifiers: ['requiresQuotes'],
        leadingUnderscore: 'allowSingleOrDouble',
      },
      {
        selector: 'parameter',
        format: ['camelCase'],
        leadingUnderscore: 'allow',
      },
      {
        selector: 'parameter',
        modifiers: ['destructured'],
        format: null,
      },
      {
        selector: 'function',
        format: ['camelCase', 'PascalCase'],
        filter: {
          regex: '^_',
          match: false,
        },
      },
      {
        selector: 'variable',
        format: ['camelCase', 'UPPER_CASE'],
        filter: {
          regex: '[^AN | DB$]',
          match: false,
        },
      },
      {
        selector: 'interface',
        format: ['PascalCase', 'camelCase'],
        prefix: ['I'],
        filter: {
          regex: '^On',
          match: false,
        },
      },
      {
        selector: 'typeAlias',
        format: ['PascalCase', 'camelCase'],
        prefix: ['T'],
      },
      {
        selector: 'class',
        format: ['PascalCase'],
      },
      {
        selector: 'typeProperty',
        format: [
          'PascalCase',
          'strictCamelCase',
          'UPPER_CASE',
        ],
      },
    ],
    'brace-style': 'off',
    '@/brace-style': [
      'error',
      '1tbs',
      { allowSingleLine: true },
    ],
    'comma-dangle': 'off',
    '@/comma-dangle': [
      'error',
      {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'always-multiline',
      },
    ],
    'comma-spacing': 'off',
    '@/comma-spacing': ['error', { before: false, after: true }],
    'func-call-spacing': 'off',
    '@/func-call-spacing': ['error', 'never'],
    'no-extra-parens': 'off',
    '@/no-extra-parens': [
      'error',
      'all',
      {
        enforceForArrowConditionals: false,
        nestedBinaryExpressions: false,
      },
    ],
    'no-extra-semi': 'off',
    '@/no-extra-semi': ['error'],
    'object-curly-spacing': 'off',
    '@/object-curly-spacing': ['error', 'always'],
    'space-before-function-paren': 'off',
    '@/space-before-function-paren': [
      'error',
      {
        anonymous: 'always',
        named: 'never',
        asyncArrow: 'always',
      },
    ],
    '@typescript-eslint/unbound-method': 'off',
    '@typescript-eslint/member-ordering': [
      'warn',
      {
        default: {
          memberTypes: [
            'signature',
            'field',
            'decorated-field',
            'decorated-get',
            'decorated-set',
            'constructor',
            'decorated-method',
            'method',
          ],
        },
        typeLiterals: {
          memberTypes: 'never',
          optionalityOrder: 'required-first',
          order: 'natural',
        },
        interfaces: {
          memberTypes: 'never',
          optionalityOrder: 'required-first',
          order: 'natural',
        },
      },
    ],
    'no-unused-vars': 'off',
    '@typescript-eslint/no-unused-vars': 'warn',
    '@typescript-eslint/prefer-string-starts-ends-with': 'error',
    'no-empty-function': 'off',
    '@typescript-eslint/no-empty-function': [
      'error',
      {
        allow: [
          'arrowFunctions',
          'functions',
          'methods',
        ],
      },
    ],
    '@typescript-eslint/prefer-includes': 'error',
    'no-use-before-define': 'off',
    '@typescript-eslint/no-use-before-define': ['error'],
    'default-param-last': 'off',
    '@typescript-eslint/default-param-last': ['error'],
    'lines-between-class-members': 'off',
    'no-unused-expressions': 'off',
    '@typescript-eslint/no-unused-expressions': ['off'],
    'no-shadow': 'off',
    '@typescript-eslint/no-shadow': ['error'],
    '@typescript-eslint/explicit-member-accessibility': [
      'warn',
      {
        accessibility: 'explicit',
        overrides: {
          accessors: 'explicit',
          constructors: 'no-public',
          methods: 'explicit',
          properties: 'explicit',
          parameterProperties: 'explicit',
        },
        ignoredMethodNames: [
          'ngOnChanges',
          'ngOnInit',
          'ngDoCheck',
          'ngAfterContentInit',
          'ngAfterContentChecked',
          'ngAfterViewInit',
          'ngAfterViewChecked',
          'ngOnDestroy',
          'intercept',
          'transform',
        ],
      },
    ],
    '@typescript-eslint/promise-function-async': 'off',
    '@typescript-eslint/consistent-type-definitions': 'off',
    'dot-notation': 'off',
    '@typescript-eslint/dot-notation': [
      'error',
      {
        allowKeywords: true,
        allowPattern: '',
        allowPrivateClassPropertyAccess: false,
        allowProtectedClassPropertyAccess: false,
        allowIndexSignaturePropertyAccess: false,
      },
    ],
    '@typescript-eslint/consistent-type-assertions': [
      'error',
      {
        assertionStyle: 'as',
        objectLiteralTypeAssertions: 'allow-as-parameter',
      },
    ],
    '@typescript-eslint/restrict-plus-operands': 'error',
    '@typescript-eslint/prefer-for-of': 'error',
    'no-magic-numbers': 'off',
    '@typescript-eslint/no-magic-numbers': 'off',
    '@typescript-eslint/prefer-enum-initializers': ['off'],
    '@typescript-eslint/ban-tslint-comment': ['error'],
    '@typescript-eslint/class-literal-property-style': ['error'],
    '@typescript-eslint/no-extraneous-class': [
      'error',
      {
        allowConstructorOnly: true,
        allowEmpty: false,
        allowStaticOnly: true,
        allowWithDecorator: true,
      },
    ],
    '@typescript-eslint/prefer-literal-enum-member': 'error',
    '@typescript-eslint/prefer-reduce-type-parameter': 'error',
    '@typescript-eslint/no-floating-promises': 'off',
    '@typescript-eslint/no-dynamic-delete': 'error',
    '@typescript-eslint/await-thenable': 'error',
    '@typescript-eslint/ban-ts-comment': [
      'error',
      {
        'ts-expect-error': 'allow-with-description',
        'ts-ignore': true,
        'ts-nocheck': true,
        'ts-check': false,
        minimumDescriptionLength: 3,
      },
    ],
    '@typescript-eslint/no-unnecessary-type-arguments': 'error',
    '@typescript-eslint/no-unnecessary-type-assertion': 'error',
    'require-await': 'off',
    '@typescript-eslint/require-await': 'off',
    '@typescript-eslint/triple-slash-reference': 'off',
    '@typescript-eslint/no-invalid-this': 'warn',
    '@typescript-eslint/prefer-readonly': 'off',
    '@typescript-eslint/array-type': 'off',
    '@typescript-eslint/no-namespace': 'off',
    '@typescript-eslint/no-implied-eval': 'error',
    '@typescript-eslint/no-loop-func': 'error',
    '@typescript-eslint/return-await': ['error', 'in-try-catch'],
    '@typescript-eslint/no-parameter-properties': 'off',
    '@typescript-eslint/no-unsafe-call': 'off',
    '@typescript-eslint/no-unnecessary-qualifier': 'error',
    '@typescript-eslint/no-unsafe-argument': 'off',
    '@typescript-eslint/no-unsafe-declaration-merging': 'error',
    '@typescript-eslint/sort-type-constituents': 'error',
    '@typescript-eslint/switch-exhaustiveness-check': 'warn',
    '@typescript-eslint/block-spacing': 'off',
    '@typescript-eslint/quotes': 'off',
    '@typescript-eslint/keyword-spacing': 'off',
    '@typescript-eslint/semi': 'off',
    '@typescript-eslint/prefer-nullish-coalescing': 'off',
    '@typescript-eslint/no-unnecessary-condition': 'off',
    '@typescript-eslint/consistent-generic-constructors': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'warn'
};
